### ISSUE TITLE
vagrant plugin install vagrant-vbguest - Needs vagrant  version 1.8.2

### ISSUE THREAD

**Issue by szoupanos** [marvel-nccr/quantum-mobile#44]
I get the following error when I run `vagrant plugin install vagrant-vbguest`

```
aiida_test@theospc38:~$ vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
/usr/lib/ruby/2.3.0/rubygems/specification.rb:946:in `all=': undefined method `group_by' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:275:in `with_isolated_gem'
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:231:in `internal_install'
	from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:102:in `install'
	from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /usr/share/vagrant/plugins/commands/plugin/action/install_gem.rb:37:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
	from /usr/share/vagrant/plugins/commands/plugin/command/base.rb:14:in `action'
	from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `each'
	from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /usr/share/vagrant/plugins/commands/plugin/command/root.rb:56:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/cli.rb:42:in `execute'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:268:in `cli'
	from /usr/bin/vagrant:173:in `<main>'
```

It seems that it is a problem of version 1.8.1
https://stackoverflow.com/questions/36811863/cant-install-vagrant-plugins-in-ubuntu-16-04

It should be mentioned that you need version 1.8.2

**Comment by ltalirz** [comment]
Thanks Spyros! On MacOS, we've actually been using vagrant 2.0.
If you can confirm that it works with vagrant 1.8.2, I'll add the ">= 1.8.2" to the readme

**Comment by szoupanos** [comment]
It works with vagrant 2.0.1, VB 5.2 (I don't know if this makes a difference) and Ubuntu 16.04

```
(qmob) aiida_test@theospc38:~/quantum-mobile$ vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Fetching: vagrant-share-1.1.9.gem (100%)
Fetching: micromachine-2.0.0.gem (100%)
Fetching: vagrant-vbguest-0.15.0.gem (100%)
Installed the plugin 'vagrant-vbguest (0.15.0)'!
(qmob) aiida_test@theospc38:~/quantum-mobile$ vagrant -v
Vagrant 2.0.1
```
